# Generated by Django 2.0.7 on 2019-04-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='file',
        ),
    ]
