# Generated by Django 2.0.7 on 2019-04-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190404_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='banner',
            new_name='banner_image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='file',
            new_name='profile_image',
        ),
    ]
